[project]
name = "pixelmind"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pyaes",
    "fpdf",
    "PyPDF2",
    "pdf2image",
    "pymupdf",
    "pymongo==4.3.3",
    "python-dotenv",
    "flask",
    "requests",
    "authlib",
    "werkzeug"
]

[tool.vercel]
entrypoint = "api/index.py:app"
